
 PARAMETER VERSION = 2.2.0


BEGIN OS
 PARAMETER OS_NAME = standalone
 PARAMETER OS_VER = 6.1
 PARAMETER PROC_INSTANCE = microblaze_0
 PARAMETER stdin = axi_uartlite_0
 PARAMETER stdout = axi_uartlite_0
END


BEGIN PROCESSOR
 PARAMETER DRIVER_NAME = cpu
 PARAMETER DRIVER_VER = 2.5
 PARAMETER HW_INSTANCE = microblaze_0
END


BEGIN DRIVER
 PARAMETER DRIVER_NAME = Convolution_Layer_32bit
 PARAMETER DRIVER_VER = 1.0
 PARAMETER HW_INSTANCE = Convolution_Layer_32bit_0
END

BEGIN DRIVER
 PARAMETER DRIVER_NAME = Maxpool_Layer_32bit
 PARAMETER DRIVER_VER = 1.0
 PARAMETER HW_INSTANCE = Maxpool_Layer_32bit_0
END

BEGIN DRIVER
 PARAMETER DRIVER_NAME = Softmax_Layer_32bit
 PARAMETER DRIVER_VER = 1.0
 PARAMETER HW_INSTANCE = Softmax_Layer_32bit_0
END

BEGIN DRIVER
 PARAMETER DRIVER_NAME = VGA_IF
 PARAMETER DRIVER_VER = 1.0
 PARAMETER HW_INSTANCE = VGA_IF_0
END

BEGIN DRIVER
 PARAMETER DRIVER_NAME = uartlite
 PARAMETER DRIVER_VER = 3.2
 PARAMETER HW_INSTANCE = axi_uartlite_0
END

BEGIN DRIVER
 PARAMETER DRIVER_NAME = intc
 PARAMETER DRIVER_VER = 3.5
 PARAMETER HW_INSTANCE = microblaze_0_axi_intc
END

BEGIN DRIVER
 PARAMETER DRIVER_NAME = bram
 PARAMETER DRIVER_VER = 4.1
 PARAMETER HW_INSTANCE = microblaze_0_local_memory_dlmb_bram_if_cntlr
END

BEGIN DRIVER
 PARAMETER DRIVER_NAME = bram
 PARAMETER DRIVER_VER = 4.1
 PARAMETER HW_INSTANCE = microblaze_0_local_memory_ilmb_bram_if_cntlr
END

BEGIN DRIVER
 PARAMETER DRIVER_NAME = mig_7series
 PARAMETER DRIVER_VER = 2.0
 PARAMETER HW_INSTANCE = mig_7series_0
END

BEGIN DRIVER
 PARAMETER DRIVER_NAME = sysmon
 PARAMETER DRIVER_VER = 7.3
 PARAMETER HW_INSTANCE = xadc_wiz_0
END


